### ISSUE TITLE
Error decoding response body when using oyster-cvm deploy

### ISSUE THREAD

**Issue by KalpitaMandal** [marlinprotocol/oyster-monorepo#116]
@Naman-Monga 

docker-compose file to recreate
```
services:
  # http proxy service
  http_proxy:
    image: kalpita888/ollama_amd64:1.0.0
    container_name: http_proxy
    command: ./app/http_proxy/http_proxy -- 127.0.0.1 5000 127.0.0.1 11434
    init: true
    network_mode: host
    volumes:
      - /app/ecdsa.sec:/app/secp.sec
```

![Image](https://github.com/user-attachments/assets/e989d833-9ede-4f77-a72e-9d90cbea44b6)
